CompileFlags:
  Add: [-std=c++17, -Wall, -Wextra, -Wconversion, -Werror, -Wunused-function, -pedantic]

Diagnostics:

  ClangTidy:

      Add: [
        modernize-*,
        performance-*,
        cppcoreguidelines-*,
        cert-*,
        readability-*,
        bugprone-*,
        misc-*,
        clang-*,
        clang-diagnostic-unused-parameter,
        boost-use-to-string,
        concurrency-thread-canceltype-asynchronous ,
        ericsson-cert-env32-c,
        google-build-explicit-make-pair,
        google-build-namespaces,
        google-build-using-namespace,
        google-explicit-constructor,
        google-global-names-in-headers,
        google-runtime-int,
        google-runtime-operator,
        mpi-buffer-deref,
        mpi-type-mismatch,
        misc-include-cleaner,
      ]

      Remove: [
        # bugprone-easily-swappable-parameters,
        modernize-use-trailing-return-type,
        # readability-identifier-length,
        # cert-err58-cpp,
        cppcoreguidelines-pro-type-vararg,
        cppcoreguidelines-pro-bounds-array-to-pointer-decay,
        cppcoreguidelines-special-member-functions,
        readability-uppercase-literal-suffix,
        modernize-avoid-c-arrays,
        # modernize-concat-nested-namespaces,

      ]
