require("hastmark.core.options")
require("hastmark.core.keymaps")
require("hastmark.core.colorscheme")
require("hastmark.plugins-setup")
require("hastmark.plugins.comment")
require("hastmark.plugins.nvim-tree")
require("hastmark.plugins.lualine")
require("hastmark.plugins.telescope")
require("hastmark.plugins.lspconfig")
require("hastmark.plugins.nvterm")
require("hastmark.plugins.autoclose")
vim.api.nvim_command('inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\\<CR>"')
